version: "3.9"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "balance"
      POSTGRES_USER: "tony"
      POSTGRES_PASSWORD: "ynot"
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"